
# Build matrix
language: node_js
matrix:
  include:

    # Run tests in Node.js 0.10 (unsupported)
    - node_js: '0.10'

    # Run tests in Node.js 0.12
    - node_js: '0.12'

    # Run tests in Node.js 4.x
    - node_js: '4'

    # Run tests in Node.js 5.x
    - node_js: '5'

  # Allow Node.js 0.10 to fail â€“ it's unsupported
  allow_failures:
    - node_js: '0.10'

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Before install
before_install:
  - npm install coveralls

# Build script
script:
  - make ci
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
