# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and lint

on:
  push:
    branches: # Run actions when code is committed to these branches
      - master
  pull_request:
    branches: # Run actions when a PR is pushed based on one of these branches
      - master
      - 1.x

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - node-version: 8.x
          lint: true # Linter is run only once to shorten the total build time

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        if: ${{ matrix.lint }}
        run: make verify
      - name: Run tests
        run: make test
